name: Publish Mod

# Run when a new tag is pushed (ie. via GitHub release or `git tag`)
on: 
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Use checkout to publish the files in your repo
      - uses: actions/checkout@v4
      - uses: GreenTF/upload-thunderstore-package@v4.3
        with:
          namespace: Ekode # the thunderstore 'team' to publish under
          description: 'R.E.P.O Modpack with all the funnies'
          token: ${{ secrets.THUNDERSTORE_SECRET_TOKEN }}
          name: REPOskour # the name of the package
          version: ${{ github.ref_name }} # Use the tag as the package version
          community: repo
          repo: thunderstore.io
          categories: | # <-- notice this pipe character
            modpacks
          deps: |
            BepInEx-BepInExPack@5.4.2100
            Zehs-REPOLib@2.0.1
            zelofi-MorePlayers@1.0.4
            nickklmao-NoLimitChatbox@1.0.1
            JacuJ-SillyWeaponSounds@1.0.1
            Zehs-ExtractionPointConfirmButton@1.1.0
            JacuJ-GnomedGnomeSounds@1.0.0
            Flopper-ImprovedStamina@1.2.0
            ColtG5-LegoGnomes@1.0.2
            BobisMods-LargePupils@1.0.2
            Lazarus-BetterTruckHeals@1.2.0
            Rebateman-LateJoin@0.1.2
            TitanVortex-BigNuke@1.0.1
            Caigan-Tokucade_Valuables@1.4.0
            IPashkaYouNot-JustEnoughTops@0.1.3
            ManancialGD-ChatClipboard@1.0.0
            DaGloobie-GloobMod@1.0.0
            pooks-PookieCosmetics@1.0.1
            Rangerbb275-REPOing_Valuables@3.0.0
            AriIcedT-ArisJunkDrawer@1.0.2
            meowing-ServingKunt@1.0.0
            Ogurtsi-MoreHats_EFT_Accessories@1.1.2
            Ogurtsi-EFT_Loot@1.0.0
            AlexKuz-Food_Valubles_Pack@1.0.4
            Spoopylocal-Lethal_Plushies@1.0.5
            Snowlance-NoDamageInShop@1.0.1
            Ako-FunnyItems@1.3.0
            ColtG5-BoomboxCart@1.1.1
            MonsterDropMods-DECSbyPulse@1.0.0
            GalaxyMods-MoreValuablesUpgrade@1.0.2
            pierre-MoreCuteness@0.1.1
            Foop-PokemonValuables@1.2.1
            nickklmao-REPOConfig@1.1.8
            Disciple-Pokeball_Valuables@1.1.3
            Nanalands-StupidHead@1.5.0
            loaforc-loaforcsSoundAPI_REPO@1.0.1
            khalliv-ShoppingListHUD@1.0.2
            BlueAmulet-REPONetworkTweaks@1.0.3
            AriIcedT-YippeeDuckEnemy@1.0.1
            BULLETBOT-ScaleInCart@1.1.8
            DiFFoZ-BepInEx_Faster_Load_AssetBundles_Patcher@1.0.1
            discjenny-CartSpeedSync@2.0.0
            Kistras-Valuables_Scanner@1.1.3
            Tolian-REPODiscordRichPresence@0.1.6
            revsolo-HSRCatCakes@1.1.0
            flipf17-DeadTTS@1.0.10
            Sticks-Super_Mario_Cosmetics@2.3.1
            Enchanted_Games-CustomGrabColor@2.1.0
            nickklmao-MenuLib@2.3.0
            Clementinise-ZoomyEyes@1.1.0
            x753_REPO-CustomColors@1.1.1
            Magic_Wesley-Wesleys_Enemies@1.1.9
            SaturnKai-Dead_Map_Access@1.0.4
            Patrick-MapVote@1.1.0
            Spawze-Spawzes_Valuables@1.3.1
            OrtonLongGaming-FreddyEnemy@1.0.3
            AriIcedT-ValuableCans@1.0.3
            Magic_Wesley-Wesleys_Valuables@1.0.2
            Yuckers-Unique_Potions@0.6.3
            BULLETBOT-MoreUpgrades@1.4.8
            Jake_n_Liv-Jake_and_Livs_Retro_Smashpack@1.1.8
            s1ckboy-SteampunkItems@1.1.1
            Bengimi-BensCosmetics@1.5.5
            CarsonJF-JBLSpeaker@1.1.0
            PaintedThornStudios-MCZombieMod@1.2.1
            Zehs-LethalCompanyValuables@1.2.1
            dig-REPOPresents@1.3.0
            YMC_MHZ-MoreHead@1.3.11
            darmuh-FovUpdate@0.2.9
            RESET-MoreHeadPlus@1.8.5
            HallowsMods-HallowsRepoCosmetics@2.9.1
            Beaniebe-Deeproot_Garden@1.0.8
            Cronchy-DeathHeadHopper@2.0.0
            AriIcedT-MinecraftStrongholdLevel@1.6.0
            Tolian-Tolian_Levels@0.2.0
            Lunoid-REPO_Alchemy@1.1.0
            Tiger_Frog-TigerFasion@1.0.11
            Maygik-MoreHeadUtilities@1.0.6
            WhalesAllAround-MikuMikuBeamer@1.0.1
            GreatColtini-MinecraftAdditions@1.0.7
            ProjectSpheroid-BaldiEnemy@1.1.1
            Rudeus-Vacuum_Enemy@1.0.12
            brookethecook-LePoissonSteveMenuMusic@1.0.2
            eth9n-Mimic@1.1.6
            EvilCheetah-TeamUpgrades@1.1.4
            CarsonJF-EnderPearlMod@2.1.1